eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://CA-LDT65QN2.groupinfra.com:8761/eureka
      instance:
        hostname: CA-LDT65QN2.groupinfra.com
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-CONTROLLER
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://PAYMENWT-CONTROLLER
          predicates:
            - Path=/payment/**


server:
    port: 8093


